### ISSUE TITLE
直播间挂机报错

### ISSUE THREAD

**Issue by zhuweitung** [orzogc/acfunlive#33]
系统环境：
```shell
Linux raspberrypi 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux
```
go版本：
```shell
go version go1.14.11 linux/arm
```

执行命令：
```shell
./acfunlive -listen -webapi -webui 
```

报错如下：
```shell
2021/04/15 19:33:53 开始在一千万个蛋壳君（716009）的直播间挂机
2021/04/15 19:33:53 开始在qyqx（378269）的直播间挂机
2021/04/15 19:33:54 Recovering from panic in wsStart(), the error is:  runtime error: invalid memory address or nil pointer dereference
2021/04/15 19:33:54 停止获取弹幕
2021/04/15 19:33:54 Recovering from panic in wsStart(), the error is:  runtime error: invalid memory address or nil pointer dereference
2021/04/15 19:33:54 停止获取弹幕
2021/04/15 19:33:59 [WARN] 因意外结束下载一千万个蛋壳君（716009）的直播弹幕，尝试重启下载
2021/04/15 19:33:59 [WARN] 因意外结束下载qyqx（378269）的直播弹幕，尝试重启下载
2021/04/15 19:33:59 Recovering from panic in wsStart(), the error is:  runtime error: invalid memory address or nil pointer dereference
2021/04/15 19:33:59 停止获取弹幕
2021/04/15 19:34:00 Recovering from panic in wsStart(), the error is:  runtime error: invalid memory address or nil pointer dereference
2021/04/15 19:34:00 停止获取弹幕
```

**Comment by orzogc** [comment]
你用的是哪个版本的代码？这个问题今天才出现的吗？

**Comment by zhuweitung** [comment]
> 你用的是哪个版本的代码？这个问题今天才出现的吗？

昨天更新到0.5.1后出现

**Comment by orzogc** [comment]
我这里没有问题，你编译最新的代码试试

**Comment by zhuweitung** [comment]
> 我这里没有问题，你编译最新的代码试试，或者检查网络连接是否正常

用最新的代码编译运行还是报上面的错，用0.5.0的代码编译报：
```shell
2021/04/15 21:33:09 登陆AcFun帐号出现错误：login() error: doRequest() error: x509: certificate is valid for *.kwd.inkuai.com, kwd.inkuai.com, not sec-cdn.gifshow.com
```

**Comment by orzogc** [comment]
我这里没有问题，应该是你那边的问题

**Comment by orzogc** [comment]
你再编译最新的代码试试

**Comment by zhuweitung** [comment]
> 你再编译最新的代码试试

好的，晚点我再试试

**Comment by bitest** [comment]
我之前编译的arm版录不了像，但是可能是环境的问题，后来我换成docker运行就正常了，你也可以试试

**Comment by zhuweitung** [comment]
> 我之前编译的arm版录不了像，但是可能是环境的问题，后来我换成docker运行就正常了，你也可以试试

嗯，晚点我试试

**Comment by zhuweitung** [comment]
> 你再编译最新的代码试试

**Comment by zhuweitung** [comment]
> 你再编译最新的代码试试

最新的代码编译报错，依赖问题
```shell
root@raspberrypi:/**/acfunlive-0.5.1/src # make
go get -d github.com/orzogc/acfunlive
cd acfunlive-ui && yarn install
yarn install v1.22.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 2.51s.
mkdir -p bin
CGO_ENABLED=0 go build -o bin
# github.com/Mrs4s/MiraiGo/utils
/root/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20210415143243-5b46d1651f6c/utils/http.go:28:9: undefined: io.ReadAll
make: *** [Makefile:29：build-go-cli] 错误 2
```

把依赖改回上个commit编译成功，但依旧报错

**Comment by orzogc** [comment]
你用最新的go 1.16.3编译试试

**Comment by zhuweitung** [comment]
> 你用最新的go 1.16.3编译试试

运行报错：
```shell
2021/04/16 20:17:32 开始在小缸和阿灿（12610197）的直播间挂机
2021/04/16 20:17:32 开始在张梓义（2889712）的直播间挂机
2021/04/16 20:17:32 开始在qyqx（378269）的直播间挂机
2021/04/16 20:17:32 开始在樱桃在不在（17062172）的直播间挂机
2021/04/16 20:17:32 开始在一千万个蛋壳君（716009）的直播间挂机
2021/04/16 20:17:32 Recovering from panic in wsStart(), the error is:  unaligned 64-bit atomic operation
2021/04/16 20:17:32 停止获取弹幕
panic: unaligned 64-bit atomic operation [recovered]
	panic: interface conversion: string is not error: missing method Error

goroutine 90 [running]:
github.com/orzogc/acfundanmu.(*AcFunLive).wsStart.func1(0x1d85080, 0x0, 0x1d8bef0)
	/root/go/pkg/mod/github.com/orzogc/acfundanmu@v0.0.0-20210416021702-5719e6a2b06a/websocket.go:56 +0xe0
panic(0x6f3580, 0x8e2268)
	/usr/local/go/src/runtime/panic.go:965 +0x174
runtime/internal/atomic.panicUnaligned()
	/usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Load64(0x1fba71c, 0x1f7df80, 0x25ae7c0)
	/usr/local/go/src/runtime/internal/atomic/asm_arm.s:263 +0x14
github.com/orzogc/acfundanmu.(*token).genPayload(0x1fba6c0, 0x8135fc, 0xe, 0x25ae7c0, 0x38, 0x38, 0x0, 0x8, 0x508f8)
	/root/go/pkg/mod/github.com/orzogc/acfundanmu@v0.0.0-20210416021702-5719e6a2b06a/proto.go:59 +0x24
github.com/orzogc/acfundanmu.(*token).register(0x1fba6c0, 0x83df5c, 0x8f2ee4, 0x1f8ab00)
	/root/go/pkg/mod/github.com/orzogc/acfundanmu@v0.0.0-20210416021702-5719e6a2b06a/proto.go:111 +0x188
github.com/orzogc/acfundanmu.(*AcFunLive).wsStart(0x1d8bef0, 0x8f2ee4, 0x1e9c4a0, 0x267e000, 0x1d85080)
	/root/go/pkg/mod/github.com/orzogc/acfundanmu@v0.0.0-20210416021702-5719e6a2b06a/websocket.go:79 +0x110
created by github.com/orzogc/acfundanmu.(*AcFunLive).StartDanmu
	/root/go/pkg/mod/github.com/orzogc/acfundanmu@v0.0.0-20210416021702-5719e6a2b06a/acfundanmu.go:538 +0x98
```

**Comment by orzogc** [comment]
你这是ARM 32的平台？好像我用的库不支持

**Comment by orzogc** [comment]
你再编译最新的代码试试

**Comment by zhuweitung** [comment]
> 你这是ARM 32的平台？好像不支持32位，我再研究一下

我树莓派重装了64位系统，问题没有复现了，可以正常使用
